(() => {
  const images = {
    startHarbor: "assets/illustrations/industrial-harbor-start.png",
    harborStudy: "assets/illustrations/harbor-study.png",
    edinburghMedicalHall: "assets/illustrations/edinburgh-medical-hall.png",
    edinburghWalk: "assets/illustrations/edinburgh-walk.png",
    cambridgeBeetleField: "assets/illustrations/cambridge-beetle-field.png",
    shrewsburyFamilyStudy: "assets/illustrations/shrewsbury-family-study.png",
    beagleDeck: "assets/illustrations/beagle-deck.png",
    stormSea: "assets/illustrations/storm-sea.png",
    seasickDarwin: "assets/illustrations/seasick-darwin-deck.png",
    seasickCaptain: "assets/illustrations/seasick-captain.png",
    seasickMate: "assets/illustrations/seasick-mate.png",
    seasickSailor: "assets/illustrations/seasick-sailor.png",
    brazilPort: "assets/illustrations/brazil-port.png",
    tierraDialogue: "assets/illustrations/tierra-dialogue.png",
    tahitiMission: "assets/illustrations/tahiti-mission.png",
    galapagosTags: "assets/illustrations/galapagos-tags.png",
    cocosCoral: "assets/illustrations/cocos-coral.png",
    londonStudy: "assets/illustrations/london-study.png",
    voyageLoading: "assets/illustrations/voyage-loading.png",
    endingDoctor: "assets/endings/doctor.png",
    endingTheologian: "assets/endings/theologian.png",
    endingFamilyFailure: "assets/endings/family-failure.png",
    endingNoseReject: "assets/endings/nose-reject.png",
    endingSeaLost: "assets/endings/sea-lost.png",
    endingSeasickDeath: "assets/endings/seasick-death.png",
    endingColonialObserver: "assets/endings/colonial-observer.png",
    endingJemmyButton: "assets/endings/jemmy-button-warning.png",
    endingMessySpecimens: "assets/endings/messy-specimens.png",
    endingCruelMalthus: "assets/endings/cruel-malthus.png",
    endingWallaceIgnore: "assets/endings/wallace-ignore.png",
    endingUnfinishedManuscript: "assets/endings/unfinished-manuscript.png",
    endingS: "assets/endings/s-ending.png",
    endingA: "assets/endings/a-ending.png",
    agentFatherBad: "assets/agent-scenes/father-bad.png",
    agentFatherGood: "assets/agent-scenes/father-good.png",
    agentFitzroyBad: "assets/agent-scenes/fitzroy-bad.png",
    agentFitzroyGood: "assets/agent-scenes/fitzroy-good.png",
    speakerSheet: "assets/portraits/interaction-speakers-sheet.png",
    darwinMaturePortrait: "assets/portraits/darwin-mature.png",
    darwinElderPortrait: "assets/portraits/darwin-elder.png",
    challengeLogo: "assets/ui/challenge-logo.png",
  };

  const bgm = {
    harborIntro: "assets/BGM/harbor-anthem.mp3",
    campus: "assets/BGM/campus.mp3",
    fatherTalk: "assets/BGM/father-talk.mp3",
    fitzroyTalk: "assets/BGM/fitzroy-talk.mp3",
    voyage: "assets/BGM/voyage.mp3",
    brazilTahiti: "assets/BGM/brazil-tahiti.mp3",
    tierra: "assets/BGM/tierra-del-fuego.mp3",
    galapagos: "assets/BGM/galapagos.mp3",
    cocos: "assets/BGM/cocos.mp3",
    england: "assets/BGM/england.mp3",
    ending: "assets/BGM/ending.mp3",
    typhoon: "assets/BGM/typhoon.mp3",
  };

  const sceneBgm = {
    "edinburgh-medicine": "campus",
    "edinburgh-medicine-retry": "campus",
    "cambridge-beetles": "campus",
    "shrewsbury-family": "fatherTalk",
    "fitzroy-interview": "fitzroyTalk",
    "storm-seasick": "typhoon",
    "storm-help": "typhoon",
    brazil: "brazilTahiti",
    "tierra-del-fuego": "tierra",
    galapagos: "galapagos",
    "galapagos-finches": "galapagos",
    "tahiti-network": "brazilTahiti",
    cocos: "cocos",
    "return-storm-event": "typhoon",
    "london-malthus": "england",
    "wallace-letter": "england",
    "publish-origin": "england",
  };

  const initialStats = {
    naturalHistory: 0,
    observation: 0,
    respect: 0,
    empireCritique: 0,
    scienceEthics: 0,
    theory: 0,
    tagAccuracy: 0,
  };

  const statLabels = {
    scienceScore: "과학적 성취도",
    ethicsScore: "인류애적 통찰력",
  };

  const statGroups = {
    summary: ["scienceScore", "ethicsScore"],
  };

  const scoreStats = {
    scienceScore: ["observation", "theory", "naturalHistory", "tagAccuracy"],
    ethicsScore: ["respect", "empireCritique", "scienceEthics"],
  };

  const noteTabs = [
    { id: "specimens", label: "표본" },
    { id: "terrain", label: "지형" },
    { id: "people", label: "사람과 사회" },
    { id: "theory", label: "이론 메모" },
    { id: "ethics", label: "윤리 메모" },
  ];

  const introLines = [
    "1809년\n 영국 슈루즈버리의 부유한 다윈 집안에서 한 아이가 태어났다.",
    "친가는 할아버지 때부터 내과의사,\n외가는 사업에 과학과 기계를 접목하여 큰 성공을 거둔 웨지우드 가문이었다.",
    "아버지 로버트 다윈은 명망 있는 내과의사였다. 환자의 속사정도 돈의 흐름도 꽤 잘 읽는 사람이었다.",
    "어머니 수잔나는 웨지우드 가문의 딸이었다. 하지만 찰스가 어릴 때 세상을 떠났기에, 형과 누나들의 손에 자랐다.",
    "이러한 집안 배경을 보면 찰스 다윈이 내과 의사가 되는 것은 정해진 수순이었다.",
    "그리고 마침내, 아버지의 기대를 등에 업고 에든버러 의학대학에 들어간다.",
  ];

  const wedgwoodLetter = {
    full: [
      "존경하는 매형께\n",
      "매형, 그동안 평안하셨는지요.",
      "다름이 아니라 찰스가 비글호 항해에 참여하고싶어한다고 들었습니다.",
      "매형께서 찰스를 아끼는 마음은 제가 십분 이해하지만 제 이야기를 한번 들어보시겠습니까.\n",
      "매형께서는 성직자로 크고 있는 찰스의 평판이 비글호로 인해 떨어질까 걱정하신다고 들었습니다.",
      "제 생각에는 이 항해가 장래의 성직자로서 찰스의 평판에 나쁜 영향을 줄 것 같지는 않습니다.",
      "오히려 찰스에게 더 명예로운 일이 될 듯합니다. 꼭 직업적으로 추구하지 않더라도 박물학 연구는 성직자에게 어울리는 일입니다.",
      "제가 생각하기론, 만약 찰스가 앞으로 2년 동안 항해를 하는 길과 이 제의를 받아들이지 않고 2년을 보내게 될 길을 비교한다면, 후자의 경우에 더 불안정해지고 정착하기 어려워질 겁니다.\n",
      "게다가 해군본부에서 그런 임무를 수행하는 데 결함이 있는 함선을 파견하지는 않을 거라고 생각합니다.",
      "찰스가 배가 허용해줄 수 있는 한도 내에서 좋은 숙소를 제공받는다면, 이 문제에 대해서는 더 이상 부연할 필요가 없겠지요.\n",
      "찰스의 직업만을 고려하면 이 원정은 쓸모없는 일이 될 수도 있습니다. 하지만 호기심 가득한 젊은이라는 점을 고려하면, 이 원정은 소수만이 경험할 수 있는 사람과 사물을 만날 좋은 기회가 될 것입니다.\n",
      "매형께선 부디 찰스에게 더 넓은 세상을 보여주셨으면 합니다.\n",
      "항상 건강하세요\n",
      "조지아 웨지우드 배상",
    ],
  };

  const endings = {
    doctor: {
      title: "새드엔딩: 의사 엔딩",
      type: "bad",
      image: "endingDoctor",
      lines: [
        "다윈은 자연사 기록을 뒤로 미루고 의학 진로에 다시 매달렸다.",
        "에든버러의 불편했던 수업은 견뎌냈지만, 자연사에 대한 그의 열망은 온전히 후회로 남았다.",
        "결과적으로 다윈은 의사가 될 수 있었지만 그는 지금 과연 행복할까.",
      ],
      advice: "자연사 연구와 관련된 선택지를 선택해보세요.",
    },
    theologian: {
      title: "새드엔딩: 신학자 엔딩",
      type: "bad",
      image: "endingTheologian",
      lines: [
        "다윈은 자연사의 호기심을 접고 신학 공부에 매달렸다.",
        "딱정벌레와 표본은 책상 가장자리로 밀려났고, 관찰 노트는 더 이상 앞으로 나아가지 못했다.",
        "그의 마음속 질문은 여전히 살아 있었지만, 이번 생의 연구는 다른 길로 접어들었다.",
      ],
      advice: "신학 공부에만 머무르지 말고, 딱정벌레와 자연사 연구의 길을 선택해보세요.",
    },
    familyFailure: {
      title: "새드엔딩: 가족 설득 실패",
      type: "bad",
      image: "endingFamilyFailure",
      lines: [
        "아버지는 항해가 장래를 망칠 무모한 일이라고 판단했다.",
        "외삼촌 조시아 웨지우드의 설득도 중요했지만, 무엇보다 중요한 것은 다윈의 의지.",
        "비글호 항해는 시작도 하기 전에 닫혔다.",
      ],
      advice: "남은 것은 다윈의 의지입니다. 의지를 강하게 피력하세요.",
    },
    noseReject: {
      title: "새드엔딩: 넌 코가 왜 그래?",
      type: "bad",
      image: "endingNoseReject",
      lines: [
        "피츠로이는 다윈의 얼굴 생김새를 성격 판단의 근거로 삼으려 했다.",
        "관상학과 골상학은 사람을 외모로 분류하려 한 19세기의 문제적 사이비 과학이었다.",
        "그 판단을 뒤집을만큼 강한 의지와 계획을 내비치지 못해 선장 신뢰를 얻지 못했다.",
      ],
      advice: "강하게 계획과 의지를 강조하여 관상이 보이지 않게 하십시오.",
    },
    seaLost: {
      title: "배드엔딩: 바다 미아",
      type: "bad",
      image: "endingSeaLost",
      lines: [
        "다윈은 사나운 바다를 버티지 못하고 충동적으로 배 밖으로 뛰어내렸다.",
        "비글호는 거친 파도 속에서 멀어졌고, 위대한 관찰 노트는 시작되기도 전에 젖어 사라졌다.",
        "귀하게 자란 청년에게 대서양은 생각보다 훨씬 차가웠다.",
        "연구 발표도 살아있어야 할 수 있는거다."
      ],
      advice: "힘들 때는 바다에 뛰어들기보다 주변 사람에게 도움을 청하세요.",
    },
    captainSeasickDeath: {
      title: "배드엔딩: 멀미로 사망",
      type: "bad",
      image: "endingSeasickDeath",
      lines: [
        "다윈은 거친 파도 속에서 도움을 청했지만, 갑판 위의 모두가 폭풍과 항로만으로도 정신이 없었다.",
        "그는 붙잡을 사람을 찾지 못한 채 갑판 구석에서 항해의 낭만이 얼마나 무서운 말인지 뼈저리게 깨달았다.",
        "비글호의 첫 관문은 표본 상자가 아니라, 살아남아 관찰할 몸 그 자체였다.",
      ],
      advice: "위기 속에서는 누구에게 도움을 청할지 고르는 판단도 중요합니다. 지금 손을 내밀 수 있는 사람을 찾아보세요.",
    },
    colonialObserver: {
      title: "새드엔딩: 식민지 관찰자",
      type: "bad",
      image: "endingColonialObserver",
      lines: [
        "다윈의 노트는 항구, 선교, 무역, 노동의 불평등을 보면서도 구조를 묻지 않았다.",
        "현지인과 원주민은 살아 있는 지식의 주체가 아니라 배경 정보처럼 처리되었다.",
        "과학 관찰이 제국 네트워크 위에서 가능했다는 점을 성찰하지 못했다.",
      ],
      advice: "현지인과 원주민을 위한 선택을 해봅시다.",
    },
    jemmyButtonDeath: {
      title: "배드엔딩: 으슥한 부름",
      type: "bad",
      image: "endingJemmyButton",
      lines: [
        "찰스 다윈이 항해를 할 무렵, 제국은 원주민들을 야만인으로 보고 교화의 대상으로 삼았다.",
        "수탈하기 위한 자원 조사와 더불어 제국은 원주민을 선교한다는 말로 교화하려했다.",
        "인종 간의 우월함과 열등함을 앞세운 연구는 윤리적으로 문제가 된다.",
        "다윈이 단순히 시대에 갇혀 판단하지 않도록 해보자.",
      ],
      advice: "한 사람의 삶을 유럽식 기준으로만 재단하지 말고, 먼저 그 사람의 말을 존중해 보세요.",
    },
    messySpecimens: {
      title: "새드엔딩: 엉망진창 표본",
      type: "bad",
      image: "endingMessySpecimens",
      lines: [
        "갈라파고스 표본은 모였지만 어느 섬에서 얻었는지 뒤섞였다.",
        "섬별 차이를 기록하지 않으면 변이와 생물지리학의 단서가 약해진다.",
        "좋은 관찰은 많이 모으는 일보다 정확히 연결하는 일에 가깝다.",
      ],
      advice: "갈라파고스에서 섬별 태그를 끝까지 지키세요.",
    },
    cruelMalthus: {
      title: "새드엔딩: 놓쳐 버린 인구론",
      type: "bad",
      image: "endingCruelMalthus",
      lines: [
        "다윈은 맬서스의 인구론을 지나쳐 버렸고, 생존과 번식의 압력을 떠올릴 결정적 단서를 놓쳤다.",
        "표본은 남았지만 변이와 환경을 하나의 설명으로 묶는 생각은 아직 선명해지지 않았다.",
        "자연선택은 우연히 떠오른 한 문장이 아니라, 관찰과 독서와 비교가 맞물릴 때 만들어지는 이론이다.",
      ],
      advice: "런던에서 인구론을 자연선택의 사고 단서로 붙잡아 보세요.",
    },
    wallaceIgnore: {
      title: "새드엔딩: 월리스 묵살",
      type: "bad",
      image: "endingWallaceIgnore",
      lines: [
        "월리스의 편지를 숨기거나 공동 발표를 피했다.",
        "비슷한 생각에 도달한 동료의 기여를 인정하지 않는 연구는 신뢰를 잃는다.",
        "『종의 기원』으로 가는 길에는 이론만큼이나 발표 윤리가 필요하다.",
        "실제 역사에서 윌리스는 다윈이 혼자 발표하는 것이 당연하다는 취지의 편지를 보낸 바 있다.",
        "따라서 다윈이 단독으로 발표했더라도 큰 문제는 없었겠지만...",
        "하지만 정말 그런 방식으로 유명해진 다윈은 행복할 수 있을까."
      ],
      advice: "월리스의 편지를 공개적으로 다루고 공동 발표를 선택하세요.",
    },
    unfinishedManuscript: {
      title: "새드엔딩: 미완성 원고",
      type: "bad",
      image: "endingUnfinishedManuscript",
      lines: [
        "다윈은 방대한 자료를 가지고 귀환했지만, 관찰과 이론을 하나로 묶을 과학적 성취도가 아직 부족했다.",
        "출판을 망설이는 사이 다른 학자가 진화론을 먼저 발표하는 것을 지켜보아야 했다.",
        "마지막 문턱에서는 충분한 증거와, 그것을 하나의 설명으로 묶을 과학적 성취가 필요했다.",
      ],
      advice: "과학적 성취도 16 이상을 확보하세요. 표본 태그, 먹이와 부리의 연결, 산호초 모델, 맬서스 독해가 핵심입니다.",
    },
    aEnding: {
      title: "노멀 엔딩: 시대에 갇힌 천재",
      type: "good",
      image: "endingA",
      lines: [
        "찰스 다윈은 기념비적인 저서 <종의 기원>을 출간하여 생물학계에 혁명을 일으켰다.",
        "과학적 성취도는 충분했지만, 항해 중 마주친 노예제와 제국의 폭력, 타문화의 목소리를 끝까지 자기 이론의 윤리로 끌어안지는 못했다.",
        "그 빈틈은 훗날 자연선택을 인간 사회의 위계와 지배를 정당화하는 말로 오독하려는 사람들에게 빌미가 되었다.",
        "위대한 발견은 완성되었지만, 그 발견이 사람에게 어떻게 쓰일지 묻는 인류애적 통찰력은 조금 모자랐다."
      ],
      advice: "과학적 성취도는 충분했지만 인류애적 통찰력 15에 닿지 못했습니다. 노예제, 원주민, 선교 네트워크, 월리스의 기여를 더 존중해 보세요.",
    },
    sEnding: {
      title: "진엔딩: 진화생물학자이자 휴머니스트",
      type: "good",
      image: "endingS",
      lines: [
        "찰스 다윈은 무사히 영국으로 귀환하여 <종의 기원>을 발표했다.",
        "섬별 표본, 부리와 먹이, 산호초의 시간, 맬서스의 단서는 하나의 과학적 설명으로 이어졌다.",
        "동시에 그는 노예제와 제국의 시선, 타문화의 목소리, 동료 연구자의 기여를 외면하지 않았다.",
        "자연선택은 인간을 줄 세우는 명분이 아니라, 모든 생명이 연결되어 있다는 깊은 통찰로 남았다.",
      ],
      advice: "과학적 성취도 16 이상과 인류애적 통찰력 15 이상을 모두 달성했습니다.",
    },
  };

  const scenes = [
    {
      id: "edinburgh-medicine",
      title: "에든버러의 해부실 안팎에서",
      location: "에든버러",
      year: "1826",
      background: "edinburghMedicalHall",
      backgroundChanges: [{ lineIndex: 2, background: "edinburghWalk" }],
      portrait: "concerned",
      text: [
        "다윈은 공부에 싫증을 느낀다.",
        "오늘도 의학서적을 펼쳤지만 아무것도 하지 못했다.",
        "다윈은 쓸쓸히 산책한다.",
      ],
      onEnter: {
        addNotes: [
          "people|에든버러: 다윈은 의학 공부를 했지만 흥미와 적성의 갈림길에 섰다.",
          "ethics|고통을 다루는 의학 수업 앞에서 느낀 불편함은 이후 생명 관찰의 태도와도 연결된다.",
        ],
      },
      choices: [
        {
          id: "choose-medicine",
          label: "그래도 의학공부를 계속한다",
          effects: { naturalHistory: -1 },
          addNotes: ["people|가족의 기대: 안정된 직업은 다윈에게 계속 압력으로 남았다."],
          mood: "concerned",
          outcomeBackground: "edinburghMedicalHall",
          outcomeCast: [{ id: "darwin", portrait: "darwin", side: "right", flipped: true }],
          outcomeLines: [
            {
              speaker: "darwin",
              name: "찰스 다윈",
              role: "에든버러 의학 수업 후",
              text: "그래... 그래도 해야지. 다윈은 마음 한구석의 찝찝함을 덮어 둔다.",
            },
          ],
          nextScene: "edinburgh-medicine-retry",
        },
        {
          id: "choose-natural-history",
          label: "생물이 더 마음에 든다",
          effects: { naturalHistory: 2, observation: 1 },
          addNotes: [
            "specimens|작은 생물과 딱정벌레: 작은 차이를 살피는 습관의 출발점.",
            "theory|관찰은 아직 이론이 아니지만, 이론의 재료가 된다.",
          ],
          mood: "curious",
          outcomeBackground: "shrewsburyFamilyStudy",
          outcomeCast: [
            { id: "father", portrait: "father", side: "left", variant: "angry" },
            { id: "darwin", portrait: "darwin", side: "right", flipped: true },
          ],
          outcomeLines: [
            {
              speaker: "darwin",
              name: "찰스 다윈",
              role: "아버지의 서재",
              text: "'아버지께 의학공부를 하고 싶지 않다고 말씀드려야지'",
            },
            {
              speaker: "darwin",
              name: "찰스 다윈",
              role: "아버지의 서재",
              text: "아버지 저는 의학이 저랑 맞지 않는 것 같습니다. 저는 자연을 관찰하고 탐구하는 것이 더 좋아요.",
            },
            {
              speaker: "father",
              name: "로버트 다윈",
              role: "아버지",
              text: "네 의견이 그렇다면 어쩔 수 없지.",
            },
            {
              speaker: "father",
              name: "로버트 다윈",
              role: "아버지",
              text: "그렇다면 케임브릿지 대학에서 신학공부를 해라.",
            },
          ],
          nextScene: "cambridge-beetles",
        },
      ],
      next: "cambridge-beetles",
    },
    {
      id: "edinburgh-medicine-retry",
      title: "눈에 밟히는 생물들",
      location: "에든버러",
      year: "1826",
      background: "edinburghMedicalHall",
      portrait: "concerned",
      text: [
        "다윈은 의학공부를 계속 했지만, 그럼에도 다양한 생물들이 눈에 밟힌다.",
      ],
      choices: [
        {
          id: "quit-school-father",
          label: "아버지께 그만둔다고 말씀드린다",
          effects: { naturalHistory: 1 },
          addNotes: ["people|진로 전환: 다윈은 의학 대신 다른 공부를 고민하게 된다."],
          mood: "concerned",
          outcomeBackground: "shrewsburyFamilyStudy",
          outcomeCast: [
            { id: "father", portrait: "father", side: "left", variant: "angry" },
            { id: "darwin", portrait: "darwin", side: "right", flipped: true },
          ],
          outcomeLines: [
            {
              speaker: "darwin",
              name: "찰스 다윈",
              role: "아버지의 서재",
              text: "아버지 저는 의학이 저랑 맞지 않는 것 같습니다. 저는 자연을 관찰하고 탐구하는 것이 더 좋아요.",
            },
            {
              speaker: "father",
              name: "로버트 다윈",
              role: "아버지",
              text: "네 의견이 그렇다면 어쩔 수 없지.",
            },
            {
              speaker: "father",
              name: "로버트 다윈",
              role: "아버지",
              text: "그렇다면 케임브릿지 대학에서 신학공부를 해라.",
            },
          ],
          nextScene: "cambridge-beetles",
        },
        {
          id: "doctor-ending-early",
          label: "아버지 말대로 의학 공부에 열중하자",
          effects: { naturalHistory: -2 },
          badEndingId: "doctor",
          mood: "concerned",
        },
        {
          id: "anatomy-tantrum",
          label: "해부학 무섭다고 떼쓰자",
          effects: { naturalHistory: -2 },
          badEndingId: "doctor",
          mood: "concerned",
          outcomeBackground: "shrewsburyFamilyStudy",
          outcomeCast: [
            { id: "father", portrait: "father", side: "left", variant: "angry" },
            { id: "darwin", portrait: "darwin", side: "right", flipped: true },
          ],
          outcomeLines: [
            {
              speaker: "darwin",
              name: "찰스 다윈",
              role: "아버지의 서재",
              text: "아버지께 해부학이 무섭다고 말씀드렸다.",
            },
            {
              speaker: "father",
              name: "로버트 다윈",
              role: "아버지",
              text: "찰스, 네가 지금 떼를 쓸 나이냐? 성인이면 성인답게 행동하거라!",
            },
            {
              speaker: "darwin",
              name: "찰스 다윈",
              role: "아버지의 서재",
              text: "'아버지 너무 무섭다. 공부.. 열심히 해야지..'",
            },
          ],
        },
      ],
      disableReflectChoice: true,
      next: "cambridge-beetles",
    },
    {
      id: "cambridge-beetles",
      title: "딱정벌레와 케임브리지의 우회로",
      location: "케임브리지",
      year: "1828-1831",
      background: "cambridgeBeetleField",
      portrait: "curious",
      text: [
        "다윈은 케임브릿지에 입학한 후 신학공부를 시작했다.",
        "하지만 케임브릿지에서 다윈은 신학 공부보다 딱정벌레에 마음을 빼앗기고 만다.",
      ],
      onEnter: {
        addNotes: ["specimens|딱정벌레 수집: 종의 차이를 구분하고 기록하는 훈련."],
      },
      choices: [
        {
          id: "beetle-focus",
          label: "딱정벌레 표본 연구를 하고 싶어",
          effects: { naturalHistory: 2, observation: 1 },
          addNotes: ["specimens|케임브리지 표본 카드: 장소, 생김새, 차이를 함께 기록한다."],
          mood: "curious",
          nextScene: "shrewsbury-family",
        },
        {
          id: "theologian-ending",
          label: "아버지 말대로 신학공부에 열중하자",
          effects: { naturalHistory: -2 },
          badEndingId: "theologian",
          mood: "concerned",
        },
      ],
      next: "shrewsbury-family",
    },
    {
      id: "shrewsbury-family",
      title: "아버지의 반대와 외삼촌의 편지",
      location: "슈루즈버리",
      year: "1831",
      background: "shrewsburyFamilyStudy",
      portrait: "concerned",
      text: [
        "비글호 승선 제안은 다윈에게 쉽게 다시 오지 않을 선택지처럼 느껴진다.",
        "하지만 아버지는 긴 항해가 젊은 다윈의 미래에 어떤 의미가 될지 확신하지 못한다.",
        "아버지는 고민 끝에 외삼촌 조시아 웨지우드와 편지를 주고받으며 생각을 정리했다.",
        "하지만 항해를 떠난다는 결정에는 다윈의 의지가 중요했다.",
      ],
      onEnter: {
        addNotes: ["people|조시아 웨지우드: 비글호 승선 허락을 얻는 데 중요한 중재자."],
      },
      next: "fitzroy-interview",
    },
    {
      id: "fitzroy-interview",
      title: "피츠로이 선장과 코의 문제",
      location: "비글호 갑판",
      year: "1831",
      background: "beagleDeck",
      portrait: "neutral",
      text: [
        "피츠로이 선장은 항해의 지휘관이자 강한 신념을 가진 사람이다.",
        "그는 다윈의 코 모양을 보고 성격과 의지를 판단하려는 듯한 말을 꺼낸다.",
      ],
      onEnter: {
        addNotes: [
          "ethics|관상학/골상학 비판: 외모로 인격과 능력을 판단하려 한 문제적 사고.",
          "people|피츠로이 선장: 비글호의 지휘관. 항해의 기회와 권한을 동시에 쥐고 있다.",
        ],
      },
      next: "brazil",
    },
    {
      id: "brazil",
      title: "열대림의 아름다움과 노예제의 그늘",
      location: "브라질",
      year: "1832",
      background: "brazilPort",
      portrait: "concerned",
      text: [
        "브라질의 숲은 다양한 생물들로 가득하지만, 항구와 농장에는 노예제가 만든 폭력이 함께 있다.",
        "비글호의 항해는 과학 탐구인 동시에 제국의 무역, 항로, 측량 정보와 맞물려 있다.",
      ],
      onEnter: {
        addNotes: [
          "people|브라질: 노예제와 대서양 무역 구조가 자연 관찰의 배경에 놓여 있다.",
          "ethics|관찰자는 자연의 아름다움과 사회적 폭력을 동시에 보아야 한다.",
        ],
      },
      choices: [
        {
          id: "listen-enslaved",
          label: "자연과 함께 노예의 모습도 기록한다",
          effects: { respect: 2, empireCritique: 1, scienceEthics: 1 },
          addNotes: ["people|노예제 증언: 사람을 정보원이 아니라 존엄한 목소리로 기록한다."],
          mood: "concerned",
          nextScene: "tierra-del-fuego",
        },
        {
          id: "ignore-slavery",
          label: "자연만 보고 사람들의 문제는 넘긴다",
          effects: { respect: -3, empireCritique: -2, scienceEthics: -1 },
          badEndingId: "colonialObserver",
          mood: "neutral",
        },
      ],
      next: "tierra-del-fuego",
    },
    {
      id: "tierra-del-fuego",
      title: "오륜델리코, 제미 버튼이라는 이름",
      location: "티에라델푸에고",
      year: "1832-1833",
      background: "tierraDialogue",
      portrait: "concerned",
      text: [
        "티에라델푸에고는 춥고 우중충했다.",
        "'제미 버튼'의 본래 이름은 '오륜델리코'였다.",
        "다윈은 사람들의 모습도 노트에 옮겨 적었다.",
        "하지만 기록이라는 건, 언제나 누군가의 시선을 통과하기 마련이다.",
      ],
      onEnter: {
        addNotes: [
          "people|오륜델리코/제미 버튼: 선교와 귀환, 이름과 정체성의 복잡한 문제를 보여준다.",
          "ethics|'문명/야만' 담론은 유럽중심주의와 연결되어 비판적으로 읽어야 한다.",
        ],
      },
      choices: [
        {
          id: "respectful-dialogue",
          label: "당신의 말을 존중하겠습니다",
          effects: { respect: 1, empireCritique: 1 },
          addNotes: ["ethics|유럽중심주의 경계: 낯섦을 열등함으로 번역하지 않는다."],
          mood: "concerned",
          nextScene: "galapagos",
        },
        {
          id: "civilization-scale",
          label: "유럽식 기준에 맞춰 분류한다",
          effects: { respect: -3, empireCritique: -2, scienceEthics: -1 },
          badEndingId: "jemmyButtonDeath",
          mood: "neutral",
        },
      ],
      next: "galapagos",
    },
    {
      id: "galapagos",
      title: "섬마다 다른 표본 카드",
      location: "갈라파고스",
      year: "1835",
      background: "galapagosTags",
      portrait: "curious",
      text: [
        "갈라파고스의 풍경은 섬마다 조금씩 분위기가 다르다.",
        "\"새의 울음소리도 약간 다른 거 같기도 하고...\"",
        "\"하... 표본이 점점 복잡해지는 것 같은데...\"",
        "다윈은 여러 섬에서 가져온 것들을 다시 펼쳐보았다.",
      ],
      onEnter: {
        addNotes: [
          "specimens|갈라파고스 표본: 섬별 위치 태그가 관찰의 핵심.",
          "theory|생물지리학: 가까운 섬 사이의 차이가 변이와 분포의 질문을 만든다.",
        ],
      },
      choices: [
        {
          id: "tag-islands",
          label: "섬 이름, 날짜, 생김새 등 표본마다 자세하게 기록해야지.",
          effects: { tagAccuracy: 2, observation: 1, theory: 1 },
          addNotes: ["specimens|완성된 표본 카드: 섬, 날짜, 형태, 관찰자를 함께 남긴다."],
          mood: "curious",
          nextScene: "galapagos-finches",
        },
        {
          id: "mix-tags",
          label: "이제 상자도 넘치고, 그냥 다 비슷해보이는데...... 대충 넣자.",
          effects: { tagAccuracy: -4, observation: -2 },
          badEndingId: "messySpecimens",
          mood: "concerned",
        },
      ],
      next: "galapagos-finches",
    },
    {
      id: "galapagos-finches",
      title: "핀치새의 부리",
      location: "갈라파고스",
      year: "1835",
      background: "galapagosTags",
      portrait: "curious",
      text: [
        "그런데, 핀치새의 부리 모양이 다른 이유는 뭘까?",
      ],
      choices: [
        {
          id: "finch-food",
          label: "먹이가 다른걸까?",
          effects: { theory: 2, observation: 1 },
          addNotes: ["theory|핀치새 부리: 섬마다 다른 먹이가 부리 모양 차이의 단서가 될 수 있다."],
          mood: "curious",
          nextScene: "storm-seasick",
        },
        {
          id: "finch-weather",
          label: "날씨가 다른걸까?",
          effects: { observation: -2, theory: -2 },
          mood: "concerned",
          nextScene: "storm-seasick",
        },
        {
          id: "finch-different-species",
          label: "아예 다른 종인걸까?",
          effects: { observation: -2, theory: -2 },
          mood: "concerned",
          nextScene: "storm-seasick",
        },
      ],
      disableReflectChoice: true,
      next: "storm-seasick",
    },
    {
      id: "storm-seasick",
      title: "사나워진 바다와 멀미",
      location: "갈라파고스 인근 바다",
      year: "1835",
      background: "seasickDarwin",
      portrait: "concerned",
      text: [
        "갈라파고스를 떠나 지나는 남태평양 부근의 바다. 파도의 높이가 심상치 않다!",
        "폭풍이 배를 뒤흔들자, 배 위는 소란스러워진다",
        "부유한 집안, 귀하게 자라 연약한 다윈은 갑판 위에서 휘청인다.",
        "극심한 멀미를 느낀 다윈은 어떻게 해야 할까.",
      ],
      onEnter: {
        addNotes: ["people|갈라파고스 인근의 멀미: 항해는 낭만적인 탐험이기 전에 몸으로 버텨야 하는 현실이었다."],
      },
      choices: [
        {
          id: "ask-help-seasick",
          label: "주변 사람들에게 도움을 요청한다",
          effects: {},
          addNotes: ["people|도움 요청: 혼자 버티기 어려울 때 주변을 보는 것도 생존 전략이다. 참고로 당시에는 멀미약으로 아편이나 코카인을 마셨다."],
          mood: "concerned",
          nextScene: "storm-help",
        },
        {
          id: "jump-overboard",
          label: "뛰어내린다",
          effects: {},
          badEndingId: "seaLost",
          mood: "concerned",
        },
      ],
      disableReflectChoice: true,
      next: "storm-help",
    },
    {
      id: "storm-help",
      title: "요동치는 갑판에서",
      location: "비글호 갑판",
      year: "1835",
      background: "seasickDarwin",
      portrait: "concerned",
      text: [
        "다윈은 난간을 붙잡고 주변을 둘러본다.",
        "누구에게 도움을 청해야 할까?",
      ],
      choices: [
        {
          id: "ask-captain-seasick",
          label: "선장에게 말한다",
          effects: {},
          badEndingId: "captainSeasickDeath",
          mood: "concerned",
          outcomeBackground: "seasickCaptain",
        },
        {
          id: "ask-mate-seasick",
          label: "부선장에게 말한다",
          effects: {},
          badEndingId: "captainSeasickDeath",
          mood: "concerned",
          outcomeBackground: "seasickMate",
        },
        {
          id: "ask-sailor-tonic",
          label: "선원에게 말한다",
          effects: { respect: 1 },
          addNotes: ["people|선원의 보약: 항해의 지식은 책상보다 갑판의 사람들에게서 나올 때도 있다."],
          mood: "determined",
          nextScene: "tahiti-network",
          outcomeBackground: "seasickSailor",
        },
      ],
      disableReflectChoice: true,
      next: "tahiti-network",
    },
    {
      id: "tahiti-network",
      title: "타히티와 뉴질랜드, 제국의 그물",
      location: "타히티/뉴질랜드",
      year: "1835",
      background: "tahitiMission",
      portrait: "concerned",
      text: [
        "타히티에서 선교 네트워크는 비글호의 이동을 돕고 현지 사회를 바꾸고 있었다.",
        "선교사, 정착민, 선원, 현지인은 같은 공간에 있지만 서로 다른 방식으로 살아간다.",
        "다윈은 항구의 풍경과 사람들의 모습을 천천히 둘러보았다.",
      ],
      onEnter: {
        addNotes: [
          "people|타히티와 뉴질랜드: 선교, 정착, 무역, 항해가 얽힌 제국 네트워크의 한 장면.",
          "ethics|현지 사회를 변화시키는 힘의 불균형을 노트에 남겨야 한다.",
        ],
      },
      choices: [
        {
          id: "network-critique",
          label: "타히티 섬에서의 불평등도 기록해야지.",
          effects: { empireCritique: 1, respect: 1, scienceEthics: 1 },
          addNotes: ["ethics|동시에 보기: 도움과 폭력, 교류와 불평등을 함께 기록한다."],
          mood: "determined",
          nextScene: "cocos",
        },
        {
          id: "mission-only",
          label: "선교가 곧 진리라고 정리한다",
          effects: { empireCritique: -2, respect: -2 },
          badEndingId: "colonialObserver",
          mood: "neutral",
        },
      ],
      next: "cocos",
    },
    {
      id: "cocos",
      title: "산호초가 말하는 느린 퍼즐",
      location: "코코스 제도",
      year: "1836",
      background: "cocosCoral",
      portrait: "curious",
      text: [
        "코코스 제도에서 다윈은 산호초와 섬의 관계를 퍼즐처럼 생각한다.",
        "화산섬이 천천히 가라앉고 산호가 자라며 띠 모양의 구조가 남았다.",
      ],
      onEnter: {
        addNotes: ["terrain|코코스 제도: 산호초 형성과 섬 침강 가설을 생각해 볼 수 있는 장소."],
      },
      choices: [
        {
          id: "model-coral",
          label: "형성 과정을 거꾸로 추론한다",
          effects: { theory: 2, observation: 1 },
          addNotes: ["theory|모델 만들기: 눈앞의 형태에서 보이지 않는 시간을 생각한다."],
          mood: "determined",
          nextScene: "return-storm-event",
        },
        {
          id: "sail-past",
          label: "위험한 암초 위치만 기록한다",
          effects: { observation: 1, theory: -1 },
          addNotes: ["terrain|항해 기록: 암초 위치는 남았지만 형성 과정 설명은 비어 있다."],
          mood: "neutral",
          nextScene: "return-storm-event",
        },
      ],
      next: "return-storm-event",
    },
    {
      id: "return-storm-event",
      title: "돌발 이벤트 발생!",
      location: "영국으로 가는 배",
      year: "1836",
      background: "stormSea",
      portrait: "concerned",
      text: [
        "바다의 폭풍이 갑자기 배를 뒤흔든다.",
        "선원들이 밧줄을 붙잡고 고함치는 사이, 선실 안의 물건들이 바닥으로 쏟아진다.",
        "몇 가지를 모두 챙길 시간은 없다.",
        "당신은 가장 먼저 무엇으로 향하겠는가? 시간이 얼마 없다!",
      ],
      choices: [
        {
          id: "storm-save-specimens",
          label: "표본 상자와 항해 지도와 기록",
          effects: { observation: 1, theory: 1, tagAccuracy: 1 },
          effectText: "과학적 성취도 +3",
          addNotes: ["specimens|폭풍 속 표본 상자: 귀국 후 연구의 재료가 될 표본과 기록을 지켜냈다."],
          mood: "determined",
          nextScene: "london-malthus",
        },
        {
          id: "storm-help-crew",
          label: "갑판 위 선원들",
          effects: { respect: 1, scienceEthics: 1 },
          effectText: "인류애적 통찰력 +2",
          addNotes: ["people|폭풍 속 선원들: 항해는 표본만이 아니라 사람들의 협력으로 이어졌다."],
          mood: "determined",
          nextScene: "london-malthus",
        },
        {
          id: "storm-personal-luggage",
          label: "개인 짐",
          effects: { observation: -1, theory: -1, respect: -1, scienceEthics: -1 },
          effectText: "과학적 성취도 -2 · 인류애적 통찰력 -2",
          addNotes: ["ethics|폭풍 속 개인 짐: 급한 순간에 무엇을 먼저 보는지가 연구와 관계의 방향을 바꾼다."],
          mood: "concerned",
          nextScene: "london-malthus",
        },
      ],
      disableReflectChoice: true,
      timeLimitSeconds: 5,
      timeoutChoiceId: "storm-personal-luggage",
      next: "london-malthus",
    },
    {
      id: "london-malthus",
      title: "런던의 책상과 맬서스의 인구론",
      location: "런던/다운 하우스",
      year: "1838",
      background: "londonStudy",
      portrait: "neutral",
      text: [
        "맬서스의 인구론이라는 책이 책상 위에 놓여 있다.",
      ],
      onEnter: {
        addNotes: [
          "theory|맬서스 읽기: 생존 경쟁의 단서를 주지만 사회적 폭력의 정당화로 읽어서는 안 된다.",
          "ethics|자연선택과 사회적 다윈주의를 구분해야 한다.",
        ],
      },
      choices: [
        {
          id: "cruel-reading",
          label: "사람의 사회와 자연을 같은 방식으로 볼 수 있을까..?",
          effects: { theory: -3, observation: 1 },
          badEndingId: "cruelMalthus",
          mood: "concerned",
        },
        {
          id: "careful-malthus",
          label: "비관적이긴 한데, 자연과 연결해 생각해볼까..",
          effects: { theory: 2, scienceEthics: 2 },
          addNotes: ["ethics|오독 경계: 자연 설명을 사람에 대한 폭력의 면허로 바꾸지 않는다."],
          mood: "determined",
          nextScene: "wallace-letter",
        },
      ],
      next: "wallace-letter",
    },
    {
      id: "wallace-letter",
      title: "월리스의 편지",
      location: "다운 하우스",
      year: "1858",
      background: "londonStudy",
      portrait: "concerned",
      text: [
        "알프레드 러셀 월리스의 편지가 도착한다.",
        "그 안에는 다윈이 오래 붙잡고 있었던 자연선택과 놀라울 만큼 가까운 생각이 들어 있었다.",
      ],
      onEnter: {
        addNotes: [
          "people|월리스의 편지: 자연선택과 가까운 생각을 담은 결정적 사건.",
          "ethics|공동 발견: 우선권과 공정한 발표 윤리가 함께 걸려 있다.",
        ],
      },
      choices: [
        {
          id: "joint-presentation",
          label: "월리스의 기여를 인정하고 공동 발표한다",
          effects: { scienceEthics: 3, theory: 1 },
          addNotes: ["ethics|월리스 인정: 『종의 기원』 전야의 중요한 윤리적 선택."],
          mood: "determined",
          nextScene: "publish-origin",
        },
        {
          id: "hide-wallace",
          label: "이 편지는 아무도 못 본 것으로 한다",
          effects: { scienceEthics: -4 },
          badEndingId: "wallaceIgnore",
          mood: "concerned",
        },
      ],
      next: "publish-origin",
    },
    {
      id: "publish-origin",
      title: "『종의 기원』으로 가는 문턱",
      location: "런던/다운 하우스",
      year: "1859",
      background: "londonStudy",
      portrait: "determined",
      text: [
        "표본과 기록들이 하나의 생각으로 이어지기 시작한다.",
        "다윈은 긴 시간 모아온 노트를 다시 펼쳐본다.",
      ],
      onEnter: {
        addNotes: ["theory|최종 원고: 관찰, 비교, 토론, 윤리가 한곳으로 모인다."],
      },
      choices: [
        {
          id: "publish",
          label: "원고를 다듬어 공동 발표한다",
          effects: {},
          addNotes: ["theory|출간 결심: 증거를 공개 토론의 장으로 내놓는다."],
          mood: "determined",
          nextScene: "__final__",
        },
        {
          id: "stay-unfinished",
          label: "아직 부족하다며 원고를 미룬다",
          effects: {},
          badEndingId: "unfinishedManuscript",
          mood: "concerned",
        },
      ],
      disableReflectChoice: true,
      next: "__final__",
    },
  ];

  window.BEAGLE_GAME_DATA = {
    images,
    bgm,
    sceneBgm,
    initialStats,
    statLabels,
    statGroups,
    scoreStats,
    noteTabs,
    introLines,
    wedgwoodLetter,
    endings,
    scenes,
  };
})();
